### PR TITLE
Adds auto reload functionality to client dev container

### LINKED ISSUE #21: enable auto-reloading of the client image in docker container
**Describe the bug**
Currently, the dev Dockerfile of the client is the same as the prod Dockerfile which serves as a prebuilt image of the client app. 
However, we would like to have auto-reloading in the dev Docker environment (like we have in the dashboard backend).

**To Reproduce**
1. navigate to the root directory of the project
2. type - `docker-compose -f docker-compose.dev.yaml up` and hit enter
3. go to `localhost:300` and check out the client app
4. make some changes in the client app and verify it doesn't reflect 

**Expected behavior**
Updating the client app code should reload and reflect changes in the docker container <3

### PR DESCRIPTION
**Pull request by XanderWatson**
Fixes #21

### CODE REVIEW

**Comment by TarunTomar122** [comment]
@XanderWatson  Build is failing can you please look into that?

**Comment by XanderWatson** [comment]
@TarunTomar122 Fixed the CI. Builds have passed now.

**Comment by kunxl-gg** [comment]
LGTM

**Comment by TarunTomar122** [comment]
bhai ne bola LGTM to LGTMT!

**Pull request merged**
